# oh-my-zsh stuff
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="gentoo"
ENABLE_CORRECTION="true"
plugins=(git ssh-agent direnv thefuck)

. $ZSH/oh-my-zsh.sh

# include .profile
. "$HOME/.profile"

# include internal zshrc
[ -f "$HOME/.zshrc-internal" ] && . "$HOME/.zshrc-internal"
