# oh-my-zsh stuff
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="gentoo"
ENABLE_CORRECTION="true"
plugins=(git ssh-agent direnv)

source $ZSH/oh-my-zsh.sh

# include .profile
source "$HOME/.profile"

# include internal zshrc
[ -f "$HOME/.zshrc-internal" ] && . "$HOME/.zshrc-internal"
